##
## STEP 1 - BUILD
##
FROM golang:1.19-alpine AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY *.go .

RUN CGO_ENABLED=0 go build -o api . 

##
## STEP 2 - DEPLOY
##
FROM scratch

WORKDIR /

COPY --from=build /app /

EXPOSE 3000

ENTRYPOINT ["/api"]